/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class Historia extends javax.swing.JFrame {

    /**
     * Creates new form Historia
     */
    public Historia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlpHistoria = new javax.swing.JLayeredPane();
        jpPrologo = new javax.swing.JPanel();
        jbNextPrologo = new javax.swing.JButton();
        jspPrologo = new javax.swing.JScrollPane();
        jtaPrologo = new javax.swing.JTextArea();
        jpFinal = new javax.swing.JPanel();
        jpCap01 = new javax.swing.JPanel();
        jspCap01 = new javax.swing.JScrollPane();
        jtaCap01 = new javax.swing.JTextArea();
        jbNextCap01 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpPrologo.setVisible(true);
        jpCap01.setVisible(false);
        jpFinal.setVisible(false);
        jlpHistoria.setBackground(new java.awt.Color(204, 255, 255));

        jpPrologo.setBackground(new java.awt.Color(0, 204, 204));

        jbNextPrologo.setFont(new java.awt.Font("BankGothic Md BT", 0, 24)); // NOI18N
        jbNextPrologo.setText("Next");
        jbNextPrologo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNextPrologoActionPerformed(evt);
            }
        });

        jtaPrologo.setEditable(false);
        jtaPrologo.setBackground(new java.awt.Color(0, 204, 204));
        jtaPrologo.setColumns(20);
        jtaPrologo.setFont(new java.awt.Font("Berlin Sans FB", 0, 40)); // NOI18N
        jtaPrologo.setLineWrap(true);
        jtaPrologo.setRows(5);
        jtaPrologo.setText("   \"Em tempos remotos, havia um poderoso feiticeiro chamado Logarim. Ele e seus ajudantes estavam tentando criar novas espécies de animais através da magia, mas em vez disso, criaram uma besta horrenda, totalmente selvagem e sedenta por sangue. Milhares de dentes afiados, 100m de altura, escamas duras como aço, essa era a aparência da criatura que tinha como único hobbie a destruição. Os aprendizes de Logarim conseguiram selar o monstro e o planeta Guthobbie nunca mais se esquecerá do dia em que cidades inteiras foram dizimadas pela criatura conhecida hoje como Belta.\"\n     Mas isso é só um conto infantil, não é mesmo? :)");
        jtaPrologo.setHighlighter(null);
        jspPrologo.setViewportView(jtaPrologo);

        javax.swing.GroupLayout jpPrologoLayout = new javax.swing.GroupLayout(jpPrologo);
        jpPrologo.setLayout(jpPrologoLayout);
        jpPrologoLayout.setHorizontalGroup(
            jpPrologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrologoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspPrologo, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
                    .addGroup(jpPrologoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbNextPrologo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpPrologoLayout.setVerticalGroup(
            jpPrologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrologoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspPrologo, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbNextPrologo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpFinal.setEnabled(false);

        javax.swing.GroupLayout jpFinalLayout = new javax.swing.GroupLayout(jpFinal);
        jpFinal.setLayout(jpFinalLayout);
        jpFinalLayout.setHorizontalGroup(
            jpFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1298, Short.MAX_VALUE)
        );
        jpFinalLayout.setVerticalGroup(
            jpFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );

        jpCap01.setBackground(new java.awt.Color(0, 204, 204));

        jtaCap01.setEditable(false);
        jtaCap01.setBackground(new java.awt.Color(0, 204, 204));
        jtaCap01.setColumns(20);
        jtaCap01.setFont(new java.awt.Font("Berlin Sans FB", 0, 40)); // NOI18N
        jtaCap01.setLineWrap(true);
        jtaCap01.setRows(5);
        jtaCap01.setText("    Aufa e Ehpol estavam prontos para mais uma aventura nas profundezas do oceano, mas dessa vez, usariam o novo feitiço que aprenderam na academia para respirar em baixo d'agua. Mergulharam e se separaram como de costume, super empolgados, pois dessa vez conseguiriam ir mais fundo. A caverna Lamda, situada na cidade de Javes, nunca antes explorada por mais ninguém além deles, era um prato cheio para os curiosos e valentes irmãos.\n     Aufa encontrou um túnel e adentrou sem pensar duas vezes. Era difícil enxergar, mas a luz que emanava da magia já bastava para ver o que estava a frente. O túnel acabou e ele encontrou uma espécie de sala subterrânea, não achou nada além de algas velhas. Decepcionado, nadou de volta para a terra firme, tal qual foi sua surpresa quando viu que estava acontecendo um terremoto. Olhou para trás e viu algo emergindo ao longe. De início parecia uma rocha, mas conforme foi saindo da água, sua silhueta foi tomando forma. Era uma criatura gigante que parecia mais com... Belta!? Não era só uma lenda? Para seu desespero, quando a criatura estava perto o suficiente para ver os mínimos detalhes de seu corpo horrendo, viu seu irmão entre as garras do monstro. Ficou surpreso quando o temível Belta... guardou seu irmão em uma espécie de bolso na barriga?\n     \n     Os jovens sempre sonharam em viver uma empolgante e perigosa aventura, parece que o momento chegou, mas não estava sendo tão divertido quanto eles imaginavam que seria. ");
        jtaCap01.setEnabled(false);
        jtaCap01.setHighlighter(null);
        jspCap01.setViewportView(jtaCap01);

        jbNextCap01.setFont(new java.awt.Font("BankGothic Md BT", 0, 24)); // NOI18N
        jbNextCap01.setText("Next");
        jbNextCap01.setEnabled(false);
        jbNextCap01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNextCap01ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCap01Layout = new javax.swing.GroupLayout(jpCap01);
        jpCap01.setLayout(jpCap01Layout);
        jpCap01Layout.setHorizontalGroup(
            jpCap01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspCap01, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCap01Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbNextCap01, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpCap01Layout.setVerticalGroup(
            jpCap01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCap01Layout.createSequentialGroup()
                .addComponent(jspCap01, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbNextCap01, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jlpHistoria.setLayer(jpPrologo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpHistoria.setLayer(jpFinal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpHistoria.setLayer(jpCap01, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpHistoriaLayout = new javax.swing.GroupLayout(jlpHistoria);
        jlpHistoria.setLayout(jlpHistoriaLayout);
        jlpHistoriaLayout.setHorizontalGroup(
            jlpHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrologo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jlpHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jlpHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jlpHistoriaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpCap01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jlpHistoriaLayout.setVerticalGroup(
            jlpHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrologo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jlpHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jlpHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jlpHistoriaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpCap01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlpHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlpHistoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbNextPrologoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNextPrologoActionPerformed
        //dispose();
        jpPrologo.setVisible(false); //jpane
        jtaPrologo.setVisible(false); // jtextarea
        jbNextPrologo.setEnabled(false); //jbutton
        jpCap01.setVisible(true);
        jtaCap01.setEnabled(true);
        jbNextCap01.setEnabled(true);
    }//GEN-LAST:event_jbNextPrologoActionPerformed

    private void jbNextCap01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNextCap01ActionPerformed
        //        jbNextCap1.setVisible(false);
        //        jpCap1.setVisible(false);
        //        jspCap1.setVisible(false);
        //        jtaCap1.setVisible(false);
        //setvisible(false);
        dispose();
        new Jogo().setVisible(true);
        
    }//GEN-LAST:event_jbNextCap01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbNextCap01;
    private javax.swing.JButton jbNextCap1;
    private javax.swing.JButton jbNextCap2;
    private javax.swing.JButton jbNextCap3;
    private javax.swing.JButton jbNextCap4;
    private javax.swing.JButton jbNextCap5;
    private javax.swing.JButton jbNextCap6;
    private javax.swing.JButton jbNextCap7;
    private javax.swing.JButton jbNextCap8;
    private javax.swing.JButton jbNextCap9;
    private javax.swing.JButton jbNextPrologo;
    private javax.swing.JLayeredPane jlpHistoria;
    private javax.swing.JPanel jpCap01;
    private javax.swing.JPanel jpFinal;
    private javax.swing.JPanel jpPrologo;
    private javax.swing.JScrollPane jspCap01;
    private javax.swing.JScrollPane jspPrologo;
    private javax.swing.JTextArea jtaCap01;
    private javax.swing.JTextArea jtaPrologo;
    // End of variables declaration//GEN-END:variables
}
